### PR TITLE
added orderbook update event

### PR DESCRIPTION
**Pull request by ridicoulous**
Hi. I added event that triggers after each order book update. It would be useful in many trading strategies to have alerts about actual prices without additional threads to monitor it. What you think about it?

### CODE REVIEW

**Comment by JKorf** [comment]
Hi, I think this is a good idea, however some books update very often. For example the Bitfinex BTC/USDT book updates every +- 1.5 milliseconds atm. So maybe a warning should be added to the code doc that it might generate a lot of events.

**Comment by ridicoulous** [comment]
> Bitfinex BTC/USDT book updates every +- 1.5 
wow. so liquid.
I added timeout for update event triggering  and comments to be careful with it. Hope it would be ok

**Comment by JKorf** [comment]
Hm the way you solved it introduces a problem though. For books which aren't updated often you'd potentially miss update triggers. Take this example:
1000ms timeout
3 events, second event 900ms after the first, third 15 seconds after the second.
First event will trigger the update, second event won't, since it is within the timeout. Now you'll only receive the update again after the next event. In this example; after 15 seconds.

I think having just a warning in the docs that the event can trigger very often is enough and let users throttle the updates themselfs.

**Comment by ridicoulous** [comment]
Really. Thank you for comments.

**Comment by JKorf** [comment]
Thanks for your contribution :)

**Comment by ridicoulous** [comment]
Hello, Jan. Could you please create a nuget package version with this updates?

**Comment by JKorf** [comment]
Hi, yes I will do so shortly. I've done more changes for version 3.0 though, so I have to update all libraries before I want to roll this out in case I find some stuff I want to change. 
I'm guessing a new version will be available end of this week.

**Pull request merged**
