### PR TITLE
Fix issue where SemaphoreSlim is released twice in RateLimitGate

### PR DESCRIPTION
**Pull request by Jonnern**
`CheckGuardsAsync` releases the semaphore when a request is rate-limited. If this task is canceled, the caller `ProcessAsync`, will also release the semaphore in the finally block. After this point, the RateLimiter is no longer thread-safe.

The implementation assumes that `CheckGuardsAsync` cannot throw a `TaskCanceledException` before the semaphore has been released.

### CODE REVIEW

**Comment by JKorf** [comment]
Hi, I had to look for a bit but you're right, good find!
Could you also add it to the `ProcessSingleAsync` method?

**Comment by Jonnern** [comment]
I updated `ProcessSingleAsync` as well and squashed the commits

**Comment by Jonnern** [comment]
@JKorf Would it be better to return
`return new CallResult(new CancellationRequestedError());` in the catch block than rethrow?

**Comment by JKorf** [comment]
Look at it now, I think you're right. If you cancel the wait then I think the exception isn't actually caught anywhere. I'll fix that with the new release

**Pull request merged**
