### PR TITLE
added request tracing id and ability to set shared HttpClient across RestClient instances

### PR DESCRIPTION
**Pull request by ridicoulous**
For more clear debug logs reading I added generation identifier for each request

### CODE REVIEW

**Comment by JKorf** [comment]
Thanks for your work. I see you made tracing optional, but I'm not seeing much reason to have it disabled, So you can just remove the it from the exchange options and always log a unique id for a request. 

Also, there are conflicts in the documentation file, please pull the latest version and rebuild your changes to fix it.

**Comment by ridicoulous** [comment]
Hello. Take a look, please

**Comment by ridicoulous** [comment]
Hi! I've fixed some little mistakes and added ability to set shared http client for preventing problems with [connection pool exhaustion ](https://stackoverflow.com/a/48778707). Also this way is very convenient to use with [.net core di](https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests) with all its benefits like [Polly](http://www.thepollyproject.org/) integration

**Comment by ridicoulous** [comment]
Just tested with my local package build. It works fine with  retry policy like 
```cs
static IAsyncPolicy<HttpResponseMessage> GetRetryPolicy()
        {
            return HttpPolicyExtensions
                .HandleTransientHttpError()
                .OrResult(msg => msg.StatusCode == System.Net.HttpStatusCode.NotFound)
                .WaitAndRetryAsync(3, retryAttempt => TimeSpan.FromSeconds(1+ retryAttempt),onRetry);
        }
```

```cs
 var serviceCollection = new ServiceCollection();
            serviceCollection.AddHttpClient<MyRestClientOptionsWithHttpClient>().AddPolicyHandler(GetRetryPolicy());
            var provider = serviceCollection.BuildServiceProvider();
            var opts = provider.GetService<MyRestClientOptionsWithHttpClient>();
            var cl = new BitmexClient(opts);
            
            var result =  cl.FakeRequest404Async().Result;
```
So in this case RestClient will receive response only after three retries:
```
2020/08/18 14:07:00:396 | Debug | Creating request for https://www.bitmex.com/api/v1/asdasd
2020/08/18 14:07:00:403 | Debug | Sending GET request to https://www.bitmex.com/api/v1/asdasd  with id bhbiept5.yrp
2020/08/18 14:07:10:833 | Debug | Error for request bhbiept5.yrp received: {"error":{"message":"Not Found","name":"HTTPError"}}
```

**Comment by ridicoulous** [comment]
Hi, @JKorf. How are you? I see you didn't have any free minute to review this updates?

**Comment by JKorf** [comment]
Thanks for your work @ridicoulous , I've made some minor changes and merged it. I'll release a new version shortly

**Comment by ridicoulous** [comment]
Some stats from Azure WebApp about registering client options via  AddHttpClient<MyOptions>():
image
It reduced TCP connections pool consumption about 5 times

**Pull request merged**
